# Site settings
title: Doing things to stuff
header-img: img/home-bg.jpg
email: adamingwersen@gmail.com
copyright_name: I don't care...
description: "Well.. It's about data"
baseurl: "/blog"
url: "http://adamingwersen.github.io"
twitter_username: adamingwersen
github_username:  adamingwersen
facebook_username:  adam.ingwersenlinnemann
email_username:  adamlinnemann@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: pygments	
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
