# Site settings
title: Doing things to stuff
header-img: img/home-bg.jpg
email: adamingwersen@gmail.com
copyright_name: Adam Ingwersen
description: "Well.. It's about data"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://adamingwersen.github.io"
twitter_username: adamingwersen
github_username:  adamingwersen
facebook_username:  blockbusterdenmark
email_username:  adamlinnemann@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
